language:
  - python

python:
  - "3.5"

sudo: required

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python manage.py test

cache:
  - flake8 --exclude polls/migrations/,manage.py  .
